// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: conversations.sql

package dbgen

import (
	"context"

	"github.com/google/uuid"
)

const createConversation = `-- name: CreateConversation :one
INSERT INTO conversations (id, user_id, title) VALUES ($1, $2, $3)
RETURNING id, user_id, title, created_at, updated_at
`

type CreateConversationParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
	Title  string
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, createConversation, arg.ID, arg.UserID, arg.Title)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteConversation = `-- name: DeleteConversation :execrows
DELETE FROM conversations WHERE id = $1 AND user_id = $2
`

type DeleteConversationParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) DeleteConversation(ctx context.Context, arg DeleteConversationParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteConversation, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ensureUser = `-- name: EnsureUser :exec
INSERT INTO users (id) VALUES ($1) ON CONFLICT (id) DO NOTHING
`

func (q *Queries) EnsureUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, ensureUser, id)
	return err
}

const getConversation = `-- name: GetConversation :one
SELECT id, user_id, title, created_at, updated_at FROM conversations WHERE id = $1 AND user_id = $2
`

type GetConversationParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetConversation(ctx context.Context, arg GetConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, getConversation, arg.ID, arg.UserID)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listConversations = `-- name: ListConversations :many
SELECT id, user_id, title, created_at, updated_at FROM conversations WHERE user_id = $1
ORDER BY updated_at DESC, id DESC
`

func (q *Queries) ListConversations(ctx context.Context, userID uuid.UUID) ([]Conversation, error) {
	rows, err := q.db.Query(ctx, listConversations, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Conversation{}
	for rows.Next() {
		var i Conversation
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const renameConversation = `-- name: RenameConversation :one
UPDATE conversations SET title = $3, updated_at = clock_timestamp()
WHERE id = $1 AND user_id = $2 RETURNING id, user_id, title, created_at, updated_at
`

type RenameConversationParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
	Title  string
}

func (q *Queries) RenameConversation(ctx context.Context, arg RenameConversationParams) (Conversation, error) {
	row := q.db.QueryRow(ctx, renameConversation, arg.ID, arg.UserID, arg.Title)
	var i Conversation
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
